# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: PowerShell script
        # You may pin to the exact commit or the version.
        # uses: Amadevus/pwsh-script@25a636480c7bc678a60bbf4e3e5ac03aca6cf2cd
        uses: Amadevus/pwsh-script@v2.0.0
        with:
          # PowerShell script to execute in Actions-hydrated context
          script: .\build.ps1
          
      - name: Upload To Github Release
        # You may pin to the exact commit or the version.
        # uses: xresloader/upload-to-github-release@3ad14478ee4fb9bd65e84c6d496a7d6862892f43
        uses: xresloader/upload-to-github-release@v1.2.2
        with:
          # The files or file patterns to upload. You can upload multiple files by split them by semicolon. You can use the glob pattern to find the files.
          file: module.zip # default is 
          # The files or file patterns to delete before uploading new files. You can delete multiple files by split them by semicolon. You can use the glob pattern to find the files.
          #delete_file: # optional, default is 
          # If you need to overwrite existing files, add overwrite: true to the with.
          overwrite: true # optional, default is false
          # The resultant deployment is a draft Release that only repository collaborators can see. This gives you an opportunity to examine and edit the draft release.
          #draft: # optional, default is true
          # The resultant deployment is a Prerelease. This gives you an opportunity to examine and edit the prerelease.
          prerelease: true # optional, default is false
          # With tags: true, your Releases deployment will trigger if and only if the build is a tagged build.
          #tags: # optional, default is false
          # Only work on these branches(splited by semicolon), set to nothing to accept all branches.
          #branches: # optional, default is 
          # With verbose: true, be verbose.
          verbose: true # optional, default is false
          # Set custom tag name.
          #tag_name: # optional, default is 
          # If try to update latest release.
          #update_latest_release: # optional, default is false
